//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace latin_lab.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresas()
        {
            this.Pacientes = new HashSet<Pacientes>();
        }
    
        public int idEmpresa { get; set; }
        public string nombre { get; set; }
        public Nullable<bool> veterinaria { get; set; }
        public string abreviado { get; set; }
        public string giroNegocio { get; set; }
        public string grupo { get; set; }
        public string contacto { get; set; }
        public string atencion { get; set; }
        public string ruc { get; set; }
        public Nullable<System.DateTime> fechaConstitucion { get; set; }
        public Nullable<System.DateTime> fechaAniversario { get; set; }
        public string cargo { get; set; }
        public string direccion { get; set; }
        public Nullable<int> idDistrito { get; set; }
        public string email { get; set; }
        public string telefono { get; set; }
        public string anexo { get; set; }
        public string fax { get; set; }
        public string homePage { get; set; }
        public string observacion { get; set; }
        public int estado { get; set; }
        public string nombreUsuario { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
    
        public virtual Distritos Distritos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pacientes> Pacientes { get; set; }
    }
}
