//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace latin_lab.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacientes
    {
        public int idPaciente { get; set; }
        public Nullable<int> idPersona { get; set; }
        public Nullable<int> idEmpresa { get; set; }
        public string numeroHistoria { get; set; }
        public string tipoFinanciador { get; set; }
        public Nullable<bool> veterinaria { get; set; }
        public string observacion { get; set; }
        public int estado { get; set; }
        public string nombreUsuario { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
    
        public virtual Empresas Empresas { get; set; }
        public virtual Personas Personas { get; set; }
    }
}
