//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace latin_lab.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personas()
        {
            this.Pacientes = new HashSet<Pacientes>();
            this.Trabajadores = new HashSet<Trabajadores>();
        }
    
        public int idPersona { get; set; }
        public string prNombre { get; set; }
        public string sgNombre { get; set; }
        public string aPaterno { get; set; }
        public string aMaterno { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public string sexo { get; set; }
        public string tipoDocumento { get; set; }
        public string numDocumento { get; set; }
        public string direccion { get; set; }
        public string numDireccion { get; set; }
        public string intDireccion { get; set; }
        public string mzaDireccion { get; set; }
        public string lteDireccion { get; set; }
        public string telefono { get; set; }
        public string celular { get; set; }
        public string trabajo { get; set; }
        public Nullable<bool> discapacitado { get; set; }
        public string tipoLocalidad { get; set; }
        public string nombreLocalidad { get; set; }
        public Nullable<int> idDistrito { get; set; }
        public int estado { get; set; }
    
        public virtual Distritos Distritos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pacientes> Pacientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trabajadores> Trabajadores { get; set; }
    }
}
