//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace latin_lab.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Servicios()
        {
            this.Tarifas = new HashSet<Tarifas>();
            this.Muestras = new HashSet<Muestras>();
        }
    
        public int idServicio { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string breve { get; set; }
        public Nullable<int> idSubClase { get; set; }
        public Nullable<int> idUnidadMedida { get; set; }
        public Nullable<int> idArea { get; set; }
        public string importeBase { get; set; }
        public Nullable<bool> veterinaria { get; set; }
        public Nullable<bool> categSocial { get; set; }
        public Nullable<bool> categTemporal { get; set; }
        public Nullable<bool> tarifaLibre { get; set; }
        public Nullable<bool> igv { get; set; }
        public Nullable<int> idTipoAydDiag { get; set; }
        public Nullable<int> idCpt { get; set; }
        public string observacion { get; set; }
        public string tipoServicio { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual Areas Areas { get; set; }
        public virtual Cpts Cpts { get; set; }
        public virtual SubClases SubClases { get; set; }
        public virtual TipoAydDiags TipoAydDiags { get; set; }
        public virtual UnidadesMedida UnidadesMedida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tarifas> Tarifas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Muestras> Muestras { get; set; }
    }
}
