//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace latin_lab.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sueldos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sueldos()
        {
            this.TrabajadorDescuentos = new HashSet<TrabajadorDescuentos>();
            this.TrabajadorIncentivo = new HashSet<TrabajadorIncentivo>();
        }
    
        public int idSueldo { get; set; }
        public Nullable<int> idTrabajador { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> montoBase { get; set; }
        public Nullable<int> cantidadDeServicios { get; set; }
        public Nullable<decimal> montoTotalPorServicios { get; set; }
        public int estadoDePago { get; set; }
        public Nullable<int> idRazonFinanciera { get; set; }
    
        public virtual RazonesFinancieras RazonesFinancieras { get; set; }
        public virtual Trabajadores Trabajadores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrabajadorDescuentos> TrabajadorDescuentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrabajadorIncentivo> TrabajadorIncentivo { get; set; }
    }
}
