//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace latin_lab.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarifas
    {
        public int idTarifa { get; set; }
        public Nullable<int> idServicio { get; set; }
        public string tipoFinanciador { get; set; }
        public Nullable<decimal> precioCalculado { get; set; }
        public Nullable<decimal> precioExcepcion { get; set; }
        public string tarifa { get; set; }
        public string observacion { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual Servicios Servicios { get; set; }
    }
}
