//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace latin_lab.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trabajadores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trabajadores()
        {
            this.Sueldos = new HashSet<Sueldos>();
            this.TrabajadorDescuentos = new HashSet<TrabajadorDescuentos>();
            this.TrabajadorIncentivo = new HashSet<TrabajadorIncentivo>();
            this.Usuarios = new HashSet<Usuarios>();
            this.Roles = new HashSet<Roles>();
        }
    
        public int idTrabajador { get; set; }
        public Nullable<int> idPersona { get; set; }
        public Nullable<int> idTipoTrabajador { get; set; }
        public Nullable<int> idArea { get; set; }
        public int estado { get; set; }
        public string nombreUsuario { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
    
        public virtual Areas Areas { get; set; }
        public virtual Personas Personas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sueldos> Sueldos { get; set; }
        public virtual TiposTrabajador TiposTrabajador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrabajadorDescuentos> TrabajadorDescuentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrabajadorIncentivo> TrabajadorIncentivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios> Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Roles> Roles { get; set; }
    }
}
