//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace latin_lab.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrabajadorDescuentos
    {
        public Nullable<int> idTrabajador { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<int> idDescuento { get; set; }
        public int estado { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idSueldo { get; set; }
        public string observacion { get; set; }
    
        public virtual Descuentos Descuentos { get; set; }
        public virtual Sueldos Sueldos { get; set; }
        public virtual Trabajadores Trabajadores { get; set; }
    }
}
